:sectnums:
:sectnumlevels: 3
:markup-in-source: verbatim,attributes,quotes
:imagesdir: ./_images/cockpit-rhel90
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:ssh_username: <Provided-By-Instructor>
:ssh_password: <Provided-By-Instructor>
:targethost_fqdn: <Provided-By-Instructor>
:subdomain: example.com
:format_cmd_exec: source,options="nowrap",subs="{markup-in-source}",role="copy"
:format_cmd_output: bash,options="nowrap",subs="{markup-in-source}"
ifeval::["%cloud_provider%" == "ec2"]
:ssh_password: %ssh_password%
:ssh_username: %ssh_username%
:targethost_fqdn: %targethost%
:subdomain: %subdomain_internal%
:format_cmd_exec: source,options="nowrap",subs="{markup-in-source}",role="execute"
endif::[]



:toc:
:toclevels: 1

= Building `wasm` Container Images

Before we go any further it is worth reiterating that in this lab we are going to build and run OCI Images containing nothing *but* the WebAssembly Byte Code itself. For example:

.A typical WebAssembly Containerfile.

[{format_cmd_output}]
----
FROM scratch
COPY ./target/wasm32-wasi/debug/wasm_app.wasm /
CMD ["/wasm_app.wasm"]
----

`FROM scratch` is most typically used for languages that output static binaries with all their dependencies such as Go. For this to work with WebAssembly we will need a WebAssembly runtime. In this lab we will see how our Container Engine, Podman, can instantiate one.

== Building the WebAssembly Image

You are certainly welcome to use your own code at this point, or your own `.wasm` artifacts. However the 2 examples in our repo have been tried and tested and one, `simple_benchmark_test`, has been designed to facilitate basic benchmarking.o


. Clone the Git Repo
+

[{format_cmd_output}]
----
$ git clone https://github.com/tonykay/wasm-oci-source-code-examples.git
----
+
.Sample Output
[source,textinfo]
----
Cloning into 'wasm-oci-source-code-examples'...
remote: Enumerating objects: 75, done.
remote: Counting objects: 100% (75/75), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 75 (delta 12), reused 71 (delta 8), pack-reused 0
Receiving objects: 100% (75/75), 29.25 KiB | 7.31 MiB/s, done.
Resolving deltas: 100% (12/12), done.
----
+

. Next `cd` into our first working directory. 
+

We are going to build a simple http server which will echo back any input.  is a good example for us, as unlike "Hello World" it runs in a detached state so we can examine the underlying runtime process and what is going o,
+

NOTE: Full disclosure this code originally came from this Second State repo before undergoing a tiny modification to allow slightly cleaner output. 
+

[{format_cmd_output}]
----
cd wasm-oci-source-code-examples/wasmedge_wasi_socket/examples/http_server/
----
+

NOTE: You can examine the source with `vim src/main.rs`.

. Compile the application to WebAssembly Byte Code by passing `cargo` the ` --target wasm32-wasi` argument
+

[{format_cmd_output}]
----
cargo build --target wasm32-wasi --release
----
+
.Sample Output

[source,textinfo]
----
... <TRUNCATED>
Compiling libc v0.2.140
   Compiling byteorder v1.4.3
   Compiling wasmedge_wasi_socket v0.4.3 (/home/devops/wasm-oci-source-code-examples/wasmedge_wasi_socket)
   Compiling trackable_derive v1.0.0
   Compiling trackable v1.2.0
   Compiling trackable v0.2.24
   Compiling bytecodec v0.4.15
   Compiling httpcodec v0.2.3
   Compiling http_server v0.1.0 (/home/devops/wasm-oci-source-code-examples/wasmedge_wasi_socket/examples/http_server)
    Finished release [optimized] target(s) in 1m 42s
----
+

. You can explore your new artifact with `tree -L 2 target/wasm32-wasi/` and other Linux tools. Take a quick look at its size ands make a mental note of that. It should be a little over 2 Megabytes.
+
[{format_cmd_output}]
----
$ ls -l target/wasm32-wasi/release/http_server.wasm
----
+
.Sample Output
[source,textinfo]
----
-rwxr-xr-x. 2 devops users 2246990 Mar 21 16:21 target/wasm32-wasi/release/http_server.wasm
----

=== Running your .wasm Artifact

In the *Setting up Rust and wasm lab you installed `wasmedge`. 

. Run your `.wasm` file, a simple http echo server with `wasmedge`. As it is a server make sure to background it by adding ` &`
+

[{format_cmd_output}]
----
$ wasmedge target/wasm32-wasi/release/http_server.wasm &
----

. Next send the server, it listens on Port `1234` some simple JSON.
+

[{format_cmd_output}]
----
curl -s -X POST http://127.0.0.1:1235 -d '{ "Event" : "WASM IO 2023 BCN" }' | jq
----
+

.Sample Output
[source,textinfo]
----
{
  "Event": "WASM IO 2023 BCN"
}
----

So now we have a working WebAssembly server.

== Building and Running a `.wasm` OCI Container image

In this section we will first build the 1 layer OCI Image with `buildah` before running it with `podman`.

. Examine the `Containerfile`
+

[{format_cmd_output}]
----
cat Containerfile
----
+
 
.Sample Output
[source,textinfo]
----
FROM scratch
COPY ./target/wasm32-wasi/release/http_server.wasm /
CMD ["/http_server.wasm"]
----
+

This is a pretty typical Containerfile for an image made from `scratch`, effectively an "empty" image base. As mentioned earlier statically compiled Go binaries are sometimes packaged like this.
+

There are some similarities between WebAssembly and Java in that both are byte code, but Java `.jar` files are combined in larger images with a Java runtime. What is happening here is we are using *OCI* images to solely distribute the Byte Code and not the runtime executable itself.
+

NOTE: Obviously is is entirely possible to create a _"traditional"_ 
+

. Build your application with `buildah`. Whilst `podman` can build OCI images `buildah` is a richer and more versatile build tool. It's beyond the scope of this lab to explore further but a simple `buildah` lab has been bundled in at the end and you can also visit the buildah website.
+
Remember in an earlier lab you installed the latest upstream versions of both `podman` and `buildah` which contain the most up to date enhancements for working with WebAssembly via `crun`
+
NOTE: Red Hat has approached Container toolchains by adopting a traditional UNIX/Linux approach where each tool focuses on doing 1 job well. The primary tools are:
+

* link:https://podman.io/[Podman] - runs OCI container images
* link:https://buildah.io/[Buildah] - builds OCI images
* link:https://github.com/containers/skopeo[Skopeo] - pulls, pushes, copies, signs, inspects OCI images and works with remote registries
** Skopeo has impressive capabilities in this space and frequently avoids the pull/push model

WARNING: You will want to substitute your own registry details in the command below when you tag your image. `-t <REGISTRY>/<REPO>/http_server:0.1.0`. This will allow you to push, pull, and sign your images in later labs. Popular registries with free accounts include:

* Quay - https://quay.io/
* Docker Hub - https://hub.docker.com/
* GitHub Container Registry - https://ghcr.io
+

[{format_cmd_output}]
----
buildah build --platform wasi/wasm --annotation "run.oci.handler=wasmedge" -t docker.io/tonykay/http_server:0.1.0 .
----
+
 
.Sample Output
[source,textinfo]
----
STEP 1/3: FROM scratch
STEP 2/3: COPY ./target/wasm32-wasi/release/http_server.wasm /
STEP 3/3: CMD ["/http_server.wasm"]
COMMIT docker.io/tonykay/http_server:0.1.0
Getting image source signatures
Copying blob a614659687ce done
Copying config cefb5b6079 done
Writing manifest to image destination
Storing signatures
--> cefb5b607989
Successfully tagged docker.io/tonykay/http_server:0.1.0
----
+

Whilst it's natural to want to go on and run our image and see if it works, lets unpack what we just did here and walk through the command.
+

[{format_cmd_output}]
----
buildah build \ <1>
  --platform wasi/wasm \ <2>
  --annotation "run.oci.handler=wasmedge" \ <3>
  -t docker.io/tonykay/http_server:0.1.0 \ <4>
  . <5>
----
. `buildah build`, standard stuff invoking buildah to build from a `Containerfile`
. `--platform wasi/wasm`, Containers are typically, unlike `.wasm` coupled to an OS and ARCH
.. You can read more about OCI Image specs link:https://github.com/opencontainers/image-spec/blob/main/image-index.md#image-index-property-descriptions[here]
. `--annotation "run.oci.handler=wasmedge"`, here we annotate the image with its handler - more on that later
. `-t docker.io/tonykay/http_server:0.1.0`, here we simply tag the image, in this case with registry, repo, name, and version 
. `.`, finally we pass in the Context Directory so buildah knows "where to look" for its assets during the build

== Summary

So in this lab we successfully built our OCI Image. In the next labs we will run and inspect the image before moving on to signing and pushing to an OCI registry such as link:https://quay.io[Quay]. 