:sectnums:
:sectnumlevels: 3
:markup-in-source: verbatim,attributes,quotes
:imagesdir: ./_images/cockpit-rhel90
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:ssh_username: <Provided-By-Instructor>
:ssh_password: <Provided-By-Instructor>
:targethost_fqdn: <Provided-By-Instructor>
:subdomain: example.com
:format_cmd_exec: source,options="nowrap",subs="{markup-in-source}",role="copy"
:format_cmd_output: bash,options="nowrap",subs="{markup-in-source}"
ifeval::["%cloud_provider%" == "ec2"]
:ssh_password: %ssh_password%
:ssh_username: %ssh_username%
:targethost_fqdn: %targethost%
:subdomain: %subdomain_internal%
:format_cmd_exec: source,options="nowrap",subs="{markup-in-source}",role="execute"
endif::[]



:toc:
:toclevels: 1

= Setup Your WebAssembly Container Runtime Environment

== Overview

In this lab we'll extend our Rust and WebAssembly environment to enable building and running WebAssembly `.wasm` Images via an external wasm runtime.

NOTE: This section is not about makine ...

== Installing your OCI and Container Toolchain

In this section we will ...

* crun
* crun-wasm
* podman
* buildah


Your development environment so far has deliberately *not* been setup with a typical container toolchain. In normal circumstances these are commonly installed and are pulled from official Red Hat repositories. In our case we want to bypass these and use upstream development versions of the toolchain.

WARNING: Doing this to production systems would typically break your support. However in our case we want to use the latest cutting edge tools as there is much current innovation in this area especially with regard to working with WebAssembly.

. Verify `podman`, `buildah`, and `crun` are *not* installed
+
[{format_cmd_output}]
----
$  type crun podman buildah
----
+
.Sample Output
[source,textinfo]
----
-bash: type: crun: not found
-bash: type: podman: not found
-bash: type: buildah: not found
----
+
NOTE: If these were installed they can simply be removed with `sudo dnf remove -y podman buildah crun`
+
. Disable `container-tools`, this will stop your development machine from pulling the official version of packages from Red Hat.
+
[{format_cmd_output}]
----
$  sudo dnf -y module disable container-tools
----
+
.Sample Output
[{format_cmd_output}]
----
Updating Subscription Management repositories.
Fast Datapath for RHEL 8 x86_64 (RPMs)                                                         8.2 kB/s | 2.4 kB     00:00
Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)                                          7.8 kB/s | 2.4 kB     00:00
Red Hat Enterprise Linux 8 for x86_64 - Supplementary (RPMs)                                   7.3 kB/s | 2.1 kB     00:00
Red Hat OpenShift Container Platform 4.12 for RHEL 8 x86_64 (RPMs)                             8.0 kB/s | 2.4 kB     00:00
Red Hat CodeReady Linux Builder for RHEL 8 x86_64 (RPMs)                                       9.4 kB/s | 2.8 kB     00:00
Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)                                       9.6 kB/s | 2.8 kB     00:00
EPEL 8                                                                                         8.3 kB/s | 2.4 kB     00:00
Dependencies resolved.
===============================================================================================================================
 Package                       Architecture                 Version                        Repository                     Size
===============================================================================================================================
Disabling modules:
 container-tools

Transaction Summary
===============================================================================================================================

Complete!
----
+
. Now add our external repo COPR podman-next
+
NOTE: TODO: add explanation and links etc re copr
+
[{format_cmd_output}]
----
$ sudo dnf copr enable -y copr.fedorainfracloud.org/rhcontainerbot/podman-next
----
+
.Sample Output
[source,textinfo]
----
Updating Subscription Management repositories.
Enabling a Copr repository. Please note that this repository is not part
of the main distribution, and quality may vary.

The Fedora Project does not exercise any power over the contents of
this repository beyond the rules outlined in the Copr FAQ at
<https://docs.pagure.org/copr.copr/user_documentation.html#what-i-can-build-in-copr>,
and packages are not held to any quality or security level.

Please do not file bug reports about these packages in Fedora
Bugzilla. In case of problems, contact the owner of this repository.
Repository successfully enabled.
----
+
. Install your Container WebAssembly Toolchain
+
[{format_cmd_output}]
----
$ sudo dnf install -y crun-wasm podman buildah
----
+
.Sample Output
[source,textinfo]
----
... <TRUNCATED>

 nftables-1:0.9.3-26.el8.x86_64
  podman-101:0.0.git.18290.149f2294-1.el8.x86_64
  shadow-utils-subid-2:4.6-17.el8.x86_64
  slirp4netns-1.2.0-10.el8.x86_64
  spdlog-1.5.0-2.el8.x86_64
  wasmedge-0.11.2-1.el8.x86_64
  yajl-2.1.0-18.el8.x86_64

Complete!
----
+
. Next verify you have the correct components
+
[{format_cmd_output}]
----
$  podman --version; buildah --version
----
+
.Sample Output
[source,textinfo]
----
podman version 4.5.0-dev
buildah version 1.30.0-dev (image-spec 1.0.2-dev, runtime-spec 1.1.0-rc.1)
----
NOTE: Your exact versions may vary, what is importnat is you are saeeing the `--dev` postfix on both `podman` and `buildah`
+
. Finally verify that the installed Container Runtime `crun` has support for `wasmedge`
+
[{format_cmd_output}]
----
$  crun --version
----
+
.Sample Output
[source,textinfo]
----
crun version UNKNOWN
commit: 6a1943f7ed540b2475a988dd237fd9a9426d14ba
rundir: /run/user/1001/crun
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +WASM:wasmedge +YAJL
----
+
NOTE: Again your exact output may vary, however key is that the final line contains the WebAssembly support `+WASM:wasmedge`

== Conclusion

We now have both a working Rust and WebAssembly development environment and a Container Toolchain to allow development and running of native WebAssembly Container images. In the next lab we will build several images and run them.

We have:

* A working Rust Development toolchain
* 

TODO: Cleanup wording


== Additional Resources

You can find more information:

    * link:https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/managing_systems_using_the_rhel_9_web_console/index[Managing Systems Using the Web Console]

[discrete]
== End of Unit

ifdef::env-github[]
link:../RHEL9-Workshop.adoc#toc[Return to TOC]
endif::[]

////
Always end files with a blank line to avoid include problems.
////
