:USER_GUID: %GUID%
:USERNAME: %USERNAME%
:markup-in-source: verbatim,attributes,quotes
:show_solution: true

[discrete]
== Delivered By

  * Tony Kay (tok@redhat.com)
 

=== Acknowledgments

  * Ivan Font (Red Hat) - extensive work providing much of the material
  ** link:https://github.com/redhat-et/wasm-demo-app[wasm-demo-app]
  * Andrew Block (Red Hat)
  * Aditya Rajan
  * Dan Walsh (Red Hat, author link:https://www.manning.com/books/podman-in-action[Podman in Action])

== Overview

First of all, THANK YOU for choosing to participate in this *WebAssembly and OCI - Better Together Workshop*.
These hands-on lab will lead you through a series of self-paced labs focussed on different areas of using wasm with OCI technologies.

In this particular workshop I've chosen to use the following mainstream technologies to explore WebAssembly and OCI:

* Rust
* `wasmedge` - integrated with `crun` ( more on that later)
* `podman`, and `buildah`
** At appropriate points we'll compare/contrast with Docker's `containerd` shim approach 

In the course of these labs we will be:

* Setup a Rust based WebAssembly development environment
* Building pure WebAssembly OCI Container Images
** i.e. with a single layer `.wasm` byte code
* Running these images via Container Engine Podman
* Signing images with Sigstore
* Pushing to a remote OCI registry
* Bonus Lab: Simple Benchmarking Container v Native wasmedge

=== Disclaimers!

NOTE: This is not a WebAssembly, or wasm, development workshop. It is focussed on using wasm and OCI technologies together and highlighting both advantages and trade-offs of this approach.

