:USER_GUID: %GUID%
:USERNAME: %USERNAME%
:markup-in-source: verbatim,attributes,quotes
:show_solution: true

[discrete]
== Presented By

  * Christoph Doerbeck
  * Eddie Chen
  * Gordon Keegan
  * Lynn Dixon

== Overview

First of all, THANK YOU for registering and participating in *The Definitive Red Hat Enterprise Linux 9 Hands-on Lab*.  
This hands-on lab will lead you through a mix of self-paced and proctored exercises covering core and updated capabilities of RHEL 9.
The lab team has worked very hard to assemble a series of exercises to introduce many of the new features and capabilities 
found in this release.  We hope you enjoy this experience and please don't hesitate to ask questions.  

=== Words of Caution

WARNING: As an administrator, you are capable of ruining your environment.  We strongly encourage you
to stick to the exercises as prescribed.  Recovery of your environment is unlikely due to limited time and resources.

WARNING: We only test with Firefox and/or Google Chrome.  Your mileage will vary using MacOS Safari or Windows Explorer.


=== Workshop Feedback

Please don't forget to review this session at the completion of this lab.  Your reviews and feedback help keep labs like these as top attractions for the Red Hat Summit.

=== Workshop Source

NOTE:  This whole effort is done using official Red Hat software and although things can likely be set up to work with upstream software components (Fedora, CentOS, etc...), alternate derivatives of RHEL are not tested or validated with these exercises.

Source for this workshop: http://github.com/xtophd/RHEL9-Workshop

== Environment Description

Exercises in this workshop require either:

  * shell access (via ssh)
  * shell access (via bookbag)
  * web gui access (via web console)

You can use the convenient shell provided to the right of these instructions (bookbag), or if you prefer you can use your preferred ssh client with the same connectivity info.  Your choice...

Activities in this workshop are performed on virtual machines running in a public cloud.  Each attendee has received their own unique environment and will be provided administrator priviledges when needed.

There are 5 systems:

  * bastion - primary system and launch point to other hosts
  * node1
  * node2
  * node3
  * leapp

The network domain is likely `example.com` but not necessarily so.  We expect most exercises and envionments will work by using the short hostnames.  So when asked to use `node1` for a unit:

  * first `ssh bastion` using the provided connection and credential info
  * and then `ssh node1`

