:USER_GUID: %GUID%
:USERNAME: %USERNAME%
:markup-in-source: verbatim,attributes,quotes
:show_solution: true

[discrete]
== Delivered By

  * Tony Kay (tok@redhat.com)
 

=== Acknowledgments

  * Ivan Font (Red Hat) - extensive work providing much of the material
  ** link:

== Overview

First of all, THANK YOU for choosing to participate in this *WebAssembly and OCI - Better Together Workshop*.
These hands-on lab will lead you through a series of self-paced labs focussed on different areas of using wasm with OCI technologies.

In this particualr workshop we've chose to use the following mainstream technologies to explore WebAssembly and OCI:

* Rust
* `wasmedge` - integrated with `crun` ( more on that later)
* `podman`, `buildah` and `skopeo`
** At appropriate points we'll compare/contrast with Docker's `containerd` shim approach 
* Microshift (Red Hat's Open)
** `CRI-0`

 and proctored exercises covering core and updated capabilities of RHEL 9.
The lab team has worked very hard to assemble a series of exercises to introduce many of the new features and capabilities 
found in this release.  We hope you enjoy this experience and please don't hesitate to ask questions.  



=== Disclaimers!

NOTE: This is not a WebAssembly, or wasm, development workshop. It is focussed on using wasm and OCI technologies together and highlighting both advantages and trade-offs of this approach.

* Building pure WebAssembly Container Images
** i.e. Single layer `.wasm` artifacts only
* Running 
* Introducing 
* Building pure WebAssembly Container Images
** i.e. Single layer `.wasm` artifacts only
